"""WorldState — the runtime facade over the persistence layer.

`ActionType.execute()` is handed a `WorldState`. Actions read and
write the world through this object only. They never touch the
SQLite session directly.

Design notes:

- WorldState wraps one Session. The session is owned by the caller
  (typically `ActionExecutor`) which decides when to commit or roll
  back. WorldState itself never commits — that keeps action execution
  atomic at the transaction level (an action either applies all of
  its side effects or none).
- The facade is intentionally narrow. It exposes only the operations
  the four v0.1 starter Actions need; richer queries are added as new
  Actions require them.
- Object Type round-trips: callers always receive freshly-validated
  pydantic models, not stale references. Mutations are explicit
  (read → mutate → save).
"""

from __future__ import annotations

import time
import uuid
from collections.abc import Iterable, Sequence
from typing import TYPE_CHECKING, Any

from sqlmodel import Session, select

from wulin_mud.core.enums import EventType, InitiatedBy, WitnessesRule

if TYPE_CHECKING:
    from wulin_mud.llm.provider import LLMProvider
from wulin_mud.ontology import (
    NPC,
    PLAYER_ID,
    ActionRecord,
    Item,
    Location,
    Memory,
    PlayerState,
)
from wulin_mud.world.persistence import (
    ItemRow,
    LocationRow,
    NpcRow,
    PlayerStateRow,
    action_record_to_row,
    item_to_row,
    load_npc,
    location_to_row,
    memory_to_row,
    player_state_to_row,
    row_to_item,
    row_to_location,
    row_to_player_state,
    save_npc,
)


def _new_memory_id() -> str:
    return f"mem_{uuid.uuid4().hex[:12]}"


def _new_action_record_id() -> str:
    return f"rec_{uuid.uuid4().hex[:12]}"


class WorldState:
    """Per-action handle on the world.

    Construct one inside a transaction, hand it to actions, commit
    after the action returns.
    """

    def __init__(
        self,
        session: Session,
        *,
        now: float | None = None,
        initiated_by: InitiatedBy = InitiatedBy.PLAYER_INPUT,
        llm_reasoning: str | None = None,
        llm: LLMProvider | None = None,
    ) -> None:
        self._session = session
        self._now = now if now is not None else time.time()
        self._initiated_by = initiated_by
        self._llm_reasoning = llm_reasoning
        self._llm = llm

    @property
    def llm(self) -> LLMProvider | None:
        """The LLM provider attached to the in-flight action, if any.

        ``None`` means no LLM is available — record_witnessed_event will
        write Memory rows with empty interpretation (test convenience).
        Production action runs always inject one.
        """
        return self._llm

    @property
    def initiated_by(self) -> InitiatedBy:
        """Who/what initiated the in-flight action. Action implementations
        thread this into the ActionRecord they write.
        """
        return self._initiated_by

    @property
    def llm_reasoning(self) -> str | None:
        return self._llm_reasoning

    # ------------------------------------------------------------------
    # Time
    # ------------------------------------------------------------------

    @property
    def now(self) -> float:
        """Current game time. Frozen for the lifetime of this WorldState
        so every Memory and ActionRecord generated by one action share
        the same timestamp.
        """
        return self._now

    # ------------------------------------------------------------------
    # NPC
    # ------------------------------------------------------------------

    def get_npc(self, npc_id: str) -> NPC | None:
        return load_npc(self._session, npc_id)

    def save_npc(self, npc: NPC) -> None:
        save_npc(self._session, npc)

    def npcs_at_location(self, location_id: str, *, exclude: Iterable[str] = ()) -> list[NPC]:
        """Return every NPC currently at `location_id`, freshly loaded.

        Used by witness resolution (SAME_LOCATION).
        """
        excl = set(exclude)
        rows = self._session.exec(
            select(NpcRow.id).where(NpcRow.current_location_id == location_id)
        ).all()
        npcs: list[NPC] = []
        for npc_id in rows:
            if npc_id in excl:
                continue
            loaded = self.get_npc(npc_id)
            if loaded is not None:
                npcs.append(loaded)
        return npcs

    # ------------------------------------------------------------------
    # Player
    # ------------------------------------------------------------------

    def get_player(self) -> PlayerState | None:
        row = self._session.get(PlayerStateRow, PLAYER_ID)
        return row_to_player_state(row) if row is not None else None

    def save_player(self, state: PlayerState) -> None:
        self._session.merge(player_state_to_row(state))

    # ------------------------------------------------------------------
    # Location
    # ------------------------------------------------------------------

    def get_location(self, location_id: str) -> Location | None:
        row = self._session.get(LocationRow, location_id)
        return row_to_location(row) if row is not None else None

    def save_location(self, location: Location) -> None:
        self._session.merge(location_to_row(location))

    # ------------------------------------------------------------------
    # Item
    # ------------------------------------------------------------------

    def get_item(self, item_id: str) -> Item | None:
        row = self._session.get(ItemRow, item_id)
        return row_to_item(row) if row is not None else None

    def save_item(self, item: Item) -> None:
        self._session.merge(item_to_row(item))

    # ------------------------------------------------------------------
    # Witness resolution
    # ------------------------------------------------------------------

    def witnesses_for(
        self,
        rule: WitnessesRule,
        *,
        location_id: str | None = None,
        explicit: Sequence[str] = (),
        exclude: Iterable[str] = (),
    ) -> list[str]:
        """Resolve the witness set per a SideEffectManifest's rule.

        Only the NPC IDs are returned (the player has no Memory store).
        Use `exclude` to drop participants who shouldn't double-up
        (rare; usually all NPCs at the location should remember).
        """
        excl = set(exclude)
        if rule is WitnessesRule.SAME_LOCATION:
            if location_id is None:
                raise ValueError("SAME_LOCATION requires location_id")
            npcs = self.npcs_at_location(location_id, exclude=excl)
            return [n.id for n in npcs]
        if rule is WitnessesRule.EXPLICIT:
            return [w for w in explicit if w not in excl]
        # FACTION_MEMBERS and RELATED_TO_PARTICIPANT arrive in v0.2 along
        # with the factions/relationship-graph propagation work.
        raise NotImplementedError(f"Witness rule {rule!r} is not implemented yet.")

    # ------------------------------------------------------------------
    # Memory + ActionRecord (system writes)
    # ------------------------------------------------------------------

    def save_memory(self, memory: Memory) -> None:
        self._session.merge(memory_to_row(memory))

    def save_action_record(self, record: ActionRecord) -> None:
        self._session.merge(action_record_to_row(record))

    async def record_witnessed_event(
        self,
        *,
        witnesses: Sequence[str],
        event_type: EventType,
        participants: Sequence[str],
        location_id: str,
        raw_facts: dict[str, Any] | None = None,
        base_importance: float = 0.5,
        base_emotional_charge: float = 0.0,
        tags: Sequence[str] = (),
    ) -> list[str]:
        """Generate one Memory row per witness for an objective event.

        If this WorldState has an ``llm`` provider attached, each
        Memory's ``interpretation`` field is filled synchronously from
        the witness's POV before the row is saved. The first element of
        ``participants`` is treated as the prime mover (the "actor"
        relative to whom relationship context is shown in the prompt).

        If no provider is attached, interpretations are left empty —
        this is the test convenience path; the write-once invariant
        means production code that fills interpretation later can still
        do so exactly once. See docs/ontology.md §2.3 and
        docs/architecture.md red line #2.

        Returns the list of new Memory IDs (in witness order).
        """
        from wulin_mud.llm.interpretation import generate_interpretation

        raw_facts_dict = dict(raw_facts or {})
        participants_list = list(participants)
        tags_list = list(tags)
        actor_id = participants_list[0] if participants_list else ""

        ids: list[str] = []
        for witness_id in witnesses:
            interpretation = ""
            if self._llm is not None:
                witness_npc = self.get_npc(witness_id)
                if witness_npc is not None:
                    draft = Memory(
                        id="mem_draft",
                        timestamp=self._now,
                        event_type=event_type,
                        participants=participants_list,
                        location_id=location_id,
                        raw_facts=raw_facts_dict,
                        npc_id=witness_id,
                        interpretation="",
                        emotional_charge=base_emotional_charge,
                        importance=base_importance,
                        tags=tags_list,
                    )
                    interpretation = await generate_interpretation(
                        provider=self._llm,
                        npc=witness_npc,
                        memory=draft,
                        actor_id=actor_id,
                    )

            mem = Memory(
                id=_new_memory_id(),
                timestamp=self._now,
                event_type=event_type,
                participants=participants_list,
                location_id=location_id,
                raw_facts=raw_facts_dict,
                npc_id=witness_id,
                interpretation=interpretation,
                emotional_charge=base_emotional_charge,
                importance=base_importance,
                tags=tags_list,
            )
            self.save_memory(mem)
            ids.append(mem.id)
        return ids

    # ------------------------------------------------------------------
    # ActionRecord factory
    # ------------------------------------------------------------------

    def build_action_record(
        self,
        *,
        action_type: str,
        actor_id: str,
        parameters: dict[str, Any],
        succeeded: bool,
        side_effects_applied: Sequence[dict[str, Any]] = (),
        memories_generated: Sequence[str] = (),
        initiated_by: InitiatedBy | None = None,
        llm_reasoning: str | None = None,
    ) -> ActionRecord:
        """Construct an ActionRecord using the current world clock.

        ``initiated_by`` / ``llm_reasoning`` default to whatever the
        executor stashed on this WorldState — actions only need to
        pass them explicitly to override (rare).
        """
        return ActionRecord(
            id=_new_action_record_id(),
            timestamp=self._now,
            action_type=action_type,
            actor_id=actor_id,
            parameters=dict(parameters),
            succeeded=succeeded,
            side_effects_applied=list(side_effects_applied),
            memories_generated=list(memories_generated),
            initiated_by=initiated_by if initiated_by is not None else self._initiated_by,
            llm_reasoning=llm_reasoning if llm_reasoning is not None else self._llm_reasoning,
        )
