"""WorldState — the runtime facade over the persistence layer.

`ActionType.execute()` is handed a `WorldState`. Actions read and
write the world through this object only. They never touch the
SQLite session directly.

Design notes:

- WorldState wraps one Session. The session is owned by the caller
  (typically `ActionExecutor`) which decides when to commit or roll
  back. WorldState itself never commits — that keeps action execution
  atomic at the transaction level (an action either applies all of
  its side effects or none).
- The facade is intentionally narrow. It exposes only the operations
  the four v0.1 starter Actions need; richer queries are added as new
  Actions require them.
- Object Type round-trips: callers always receive freshly-validated
  pydantic models, not stale references. Mutations are explicit
  (read → mutate → save).
"""

from __future__ import annotations

import time
import uuid
from collections.abc import Iterable, Sequence
from typing import TYPE_CHECKING, Any

from sqlmodel import Session, select

from wulin_mud.core.enums import EventType, InitiatedBy, WitnessesRule

if TYPE_CHECKING:
    from wulin_mud.llm.provider import LLMProvider
from wulin_mud.ontology import (
    NPC,
    PLAYER_ID,
    ActionRecord,
    Item,
    Location,
    Memory,
    PlayerState,
)
from wulin_mud.world.persistence import (
    ItemRow,
    LocationRow,
    MemoryRow,
    NpcRow,
    PlayerStateRow,
    action_record_to_row,
    item_to_row,
    load_npc,
    location_to_row,
    memory_to_row,
    player_state_to_row,
    row_to_item,
    row_to_location,
    row_to_memory,
    row_to_player_state,
    save_npc,
)


def _new_memory_id() -> str:
    return f"mem_{uuid.uuid4().hex[:12]}"


def _new_action_record_id() -> str:
    return f"rec_{uuid.uuid4().hex[:12]}"


class WorldState:
    """Per-action handle on the world.

    Construct one inside a transaction, hand it to actions, commit
    after the action returns.
    """

    def __init__(
        self,
        session: Session,
        *,
        now: float | None = None,
        initiated_by: InitiatedBy = InitiatedBy.PLAYER_INPUT,
        llm_reasoning: str | None = None,
        llm: LLMProvider | None = None,
    ) -> None:
        self._session = session
        self._now = now if now is not None else time.time()
        self._initiated_by = initiated_by
        self._llm_reasoning = llm_reasoning
        self._llm = llm

    @property
    def llm(self) -> LLMProvider | None:
        """The LLM provider attached to the in-flight action, if any.

        ``None`` means no LLM is available — record_witnessed_event will
        write Memory rows with empty interpretation (test convenience).
        Production action runs always inject one.
        """
        return self._llm

    @property
    def initiated_by(self) -> InitiatedBy:
        """Who/what initiated the in-flight action. Action implementations
        thread this into the ActionRecord they write.
        """
        return self._initiated_by

    @property
    def llm_reasoning(self) -> str | None:
        return self._llm_reasoning

    # ------------------------------------------------------------------
    # Time
    # ------------------------------------------------------------------

    @property
    def now(self) -> float:
        """Current game time. Frozen for the lifetime of this WorldState
        so every Memory and ActionRecord generated by one action share
        the same timestamp.
        """
        return self._now

    # ------------------------------------------------------------------
    # NPC
    # ------------------------------------------------------------------

    def get_npc(self, npc_id: str) -> NPC | None:
        return load_npc(self._session, npc_id)

    def save_npc(self, npc: NPC) -> None:
        save_npc(self._session, npc)

    def npcs_at_location(self, location_id: str, *, exclude: Iterable[str] = ()) -> list[NPC]:
        """Return every NPC currently at `location_id`, freshly loaded.

        Used by witness resolution (SAME_LOCATION).
        """
        excl = set(exclude)
        rows = self._session.exec(
            select(NpcRow.id).where(NpcRow.current_location_id == location_id)
        ).all()
        npcs: list[NPC] = []
        for npc_id in rows:
            if npc_id in excl:
                continue
            loaded = self.get_npc(npc_id)
            if loaded is not None:
                npcs.append(loaded)
        return npcs

    # ------------------------------------------------------------------
    # Player
    # ------------------------------------------------------------------

    def get_player(self) -> PlayerState | None:
        row = self._session.get(PlayerStateRow, PLAYER_ID)
        return row_to_player_state(row) if row is not None else None

    def save_player(self, state: PlayerState) -> None:
        self._session.merge(player_state_to_row(state))

    # ------------------------------------------------------------------
    # Location
    # ------------------------------------------------------------------

    def get_location(self, location_id: str) -> Location | None:
        row = self._session.get(LocationRow, location_id)
        return row_to_location(row) if row is not None else None

    def save_location(self, location: Location) -> None:
        self._session.merge(location_to_row(location))

    # ------------------------------------------------------------------
    # Item
    # ------------------------------------------------------------------

    def get_item(self, item_id: str) -> Item | None:
        row = self._session.get(ItemRow, item_id)
        return row_to_item(row) if row is not None else None

    def save_item(self, item: Item) -> None:
        self._session.merge(item_to_row(item))

    # ------------------------------------------------------------------
    # Witness resolution
    # ------------------------------------------------------------------

    def witnesses_for(
        self,
        rule: WitnessesRule,
        *,
        location_id: str | None = None,
        explicit: Sequence[str] = (),
        exclude: Iterable[str] = (),
    ) -> list[str]:
        """Resolve the witness set per a SideEffectManifest's rule.

        Only the NPC IDs are returned (the player has no Memory store).
        Use `exclude` to drop participants who shouldn't double-up
        (rare; usually all NPCs at the location should remember).
        """
        excl = set(exclude)
        if rule is WitnessesRule.SAME_LOCATION:
            if location_id is None:
                raise ValueError("SAME_LOCATION requires location_id")
            npcs = self.npcs_at_location(location_id, exclude=excl)
            return [n.id for n in npcs]
        if rule is WitnessesRule.EXPLICIT:
            return [w for w in explicit if w not in excl]
        # FACTION_MEMBERS and RELATED_TO_PARTICIPANT arrive in v0.2 along
        # with the factions/relationship-graph propagation work.
        raise NotImplementedError(f"Witness rule {rule!r} is not implemented yet.")

    # ------------------------------------------------------------------
    # Memory + ActionRecord (system writes + retrieval)
    # ------------------------------------------------------------------

    def save_memory(self, memory: Memory) -> None:
        self._session.merge(memory_to_row(memory))

    def save_action_record(self, record: ActionRecord) -> None:
        self._session.merge(action_record_to_row(record))

    def retrieve_relevant_memories(
        self,
        npc_id: str,
        *,
        top_n: int = 10,
        query_tags: Sequence[str] = (),
        include_archived: bool = False,
    ) -> list[Memory]:
        """Return the top-N memories belonging to ``npc_id``, ranked by
        importance × tag_relevance (see
        :mod:`wulin_mud.world.memory_retrieval`).

        Memories tagged :data:`ARCHIVED_TAG` (importance decayed below
        :data:`IMPORTANCE_FLOOR` during a tick) are excluded by default.
        They remain in the DB for forensics; pass
        ``include_archived=True`` to see them.

        Pure read — does NOT update ``last_recalled_at``. Call
        :meth:`mark_memories_recalled` if the memory is being used in
        a prompt and should be protected from the next tick's decay.
        """
        from wulin_mud.world.memory_retrieval import ARCHIVED_TAG, score_memory

        rows = self._session.exec(select(MemoryRow).where(MemoryRow.npc_id == npc_id)).all()
        memories = [row_to_memory(r) for r in rows]
        if not include_archived:
            memories = [m for m in memories if ARCHIVED_TAG not in m.tags]
        if not memories:
            return []
        memories.sort(
            key=lambda m: score_memory(m, query_tags=query_tags),
            reverse=True,
        )
        return memories[:top_n]

    def retrieve_recent_dialogue(
        self,
        npc_id: str,
        *,
        with_actor_id: str,
        max_turns: int = 6,
    ) -> list[Memory]:
        """Last `max_turns` dialogue rows between ``npc_id`` and
        ``with_actor_id``, oldest first (so the prompt can render them
        in conversation order).

        A "dialogue row" is a Memory with event_type=TALKED, owned by
        ``npc_id``, whose participants include ``with_actor_id``.
        """
        rows = self._session.exec(
            select(MemoryRow)
            .where(
                MemoryRow.npc_id == npc_id,
                MemoryRow.event_type == EventType.TALKED.value,
            )
            .order_by(MemoryRow.timestamp.desc())  # type: ignore[attr-defined]
        ).all()
        recent: list[Memory] = []
        for row in rows:
            mem = row_to_memory(row)
            if with_actor_id in mem.participants:
                recent.append(mem)
            if len(recent) >= max_turns:
                break
        recent.reverse()  # oldest first
        return recent

    # ------------------------------------------------------------------
    # Bulk operations used by system (tick) actions
    # ------------------------------------------------------------------

    def decay_memories_bulk(self, *, tick_dt_game_days: float) -> dict[str, int]:
        """Apply one tick of decay to every Memory in the DB.

        Per docs/ontology.md §2.3:
        - importance *= exp(-decay_rate * tick_dt_game_days)
        - Memories recalled within the current tick window
          (last_recalled_at >= now - tick_dt) skip decay this tick.
        - Memories whose new importance drops below IMPORTANCE_FLOOR
          get tagged ARCHIVED_TAG and are excluded from default
          retrieval going forward.

        Returns a stats dict for the caller (action) to put on its
        ActionRecord.side_effects_applied.
        """
        import math

        from wulin_mud.world.memory_retrieval import ARCHIVED_TAG, IMPORTANCE_FLOOR

        if tick_dt_game_days < 0:
            raise ValueError("tick_dt_game_days must be non-negative")
        tick_dt_seconds = tick_dt_game_days * 86_400.0
        rows = self._session.exec(select(MemoryRow)).all()
        decayed = 0
        protected = 0
        archived = 0
        for row in rows:
            if ARCHIVED_TAG in row.tags:
                continue
            if (
                row.last_recalled_at is not None
                and tick_dt_seconds > 0
                and (self._now - row.last_recalled_at) <= tick_dt_seconds
            ):
                protected += 1
                continue
            factor = math.exp(-row.decay_rate * tick_dt_game_days)
            row.importance = row.importance * factor
            decayed += 1
            if row.importance < IMPORTANCE_FLOOR:
                row.tags = [*row.tags, ARCHIVED_TAG]
                archived += 1
            self._session.add(row)
        return {"decayed": decayed, "protected_by_recall": protected, "archived": archived}

    def drift_mood_bulk(
        self,
        *,
        alpha: float = 0.1,
        target_arousal: float = 0.3,
    ) -> dict[str, int]:
        """Apply one tick of mood drift to every NPC.

        Per docs/architecture.md §4: "NPC 心情漂移：基于性格的基线和最近事件，
        每个 NPC 的 mood 向其稳态回归..."

        v0.1 model:
          target_valence = 0.3 × (extraversion - neuroticism)
          target_arousal = 0.3 (constant; later sprints will derive it
                                from personality + recent events)
          new = old + alpha × (target - old)        // alpha=0.1

        Returns a stats dict (count of NPCs moved).
        """
        from wulin_mud.world.persistence import row_to_npc

        if not (0.0 < alpha <= 1.0):
            raise ValueError("alpha must be in (0, 1]")

        rows = self._session.exec(select(NpcRow)).all()
        moved = 0
        for row in rows:
            npc = row_to_npc(row)
            p = npc.personality
            target_valence = 0.3 * (p.extraversion - p.neuroticism)
            new_valence = npc.mood.valence + alpha * (target_valence - npc.mood.valence)
            new_arousal = npc.mood.arousal + alpha * (target_arousal - npc.mood.arousal)
            # clamp to valid ranges
            new_valence = max(-1.0, min(1.0, new_valence))
            new_arousal = max(0.0, min(1.0, new_arousal))
            row.mood = {"valence": new_valence, "arousal": new_arousal}
            self._session.add(row)
            moved += 1
        return {"moved": moved}

    def mark_memories_recalled(
        self, memory_ids: Iterable[str], *, at_time: float | None = None
    ) -> None:
        """Set last_recalled_at on the given memories.

        last_recalled_at is NOT write-once (only ``interpretation`` is),
        so this is a plain UPDATE — it doesn't trip the immutability
        trigger. Bumping it makes the memory decay slower going forward,
        which is the docs/ontology.md §2.3 "被想起的事衰减更慢" rule.
        """
        ts = at_time if at_time is not None else self._now
        for mem_id in memory_ids:
            row = self._session.get(MemoryRow, mem_id)
            if row is None:
                continue
            row.last_recalled_at = ts
            self._session.add(row)

    async def record_witnessed_event(
        self,
        *,
        witnesses: Sequence[str],
        event_type: EventType,
        participants: Sequence[str],
        location_id: str,
        raw_facts: dict[str, Any] | None = None,
        base_importance: float = 0.5,
        base_emotional_charge: float = 0.0,
        tags: Sequence[str] = (),
    ) -> list[str]:
        """Generate one Memory row per witness for an objective event.

        If this WorldState has an ``llm`` provider attached, each
        Memory's ``interpretation`` field is filled synchronously from
        the witness's POV before the row is saved. The first element of
        ``participants`` is treated as the prime mover (the "actor"
        relative to whom relationship context is shown in the prompt).

        If no provider is attached, interpretations are left empty —
        this is the test convenience path; the write-once invariant
        means production code that fills interpretation later can still
        do so exactly once. See docs/ontology.md §2.3 and
        docs/architecture.md red line #2.

        Returns the list of new Memory IDs (in witness order).
        """
        from wulin_mud.llm.interpretation import generate_interpretation

        raw_facts_dict = dict(raw_facts or {})
        participants_list = list(participants)
        tags_list = list(tags)
        actor_id = participants_list[0] if participants_list else ""

        ids: list[str] = []
        for witness_id in witnesses:
            interpretation = ""
            if self._llm is not None:
                witness_npc = self.get_npc(witness_id)
                if witness_npc is not None:
                    draft = Memory(
                        id="mem_draft",
                        timestamp=self._now,
                        event_type=event_type,
                        participants=participants_list,
                        location_id=location_id,
                        raw_facts=raw_facts_dict,
                        npc_id=witness_id,
                        interpretation="",
                        emotional_charge=base_emotional_charge,
                        importance=base_importance,
                        tags=tags_list,
                    )
                    interpretation = await generate_interpretation(
                        provider=self._llm,
                        npc=witness_npc,
                        memory=draft,
                        actor_id=actor_id,
                    )

            mem = Memory(
                id=_new_memory_id(),
                timestamp=self._now,
                event_type=event_type,
                participants=participants_list,
                location_id=location_id,
                raw_facts=raw_facts_dict,
                npc_id=witness_id,
                interpretation=interpretation,
                emotional_charge=base_emotional_charge,
                importance=base_importance,
                tags=tags_list,
            )
            self.save_memory(mem)
            ids.append(mem.id)
        return ids

    # ------------------------------------------------------------------
    # ActionRecord factory
    # ------------------------------------------------------------------

    def build_action_record(
        self,
        *,
        action_type: str,
        actor_id: str,
        parameters: dict[str, Any],
        succeeded: bool,
        side_effects_applied: Sequence[dict[str, Any]] = (),
        memories_generated: Sequence[str] = (),
        initiated_by: InitiatedBy | None = None,
        llm_reasoning: str | None = None,
    ) -> ActionRecord:
        """Construct an ActionRecord using the current world clock.

        ``initiated_by`` / ``llm_reasoning`` default to whatever the
        executor stashed on this WorldState — actions only need to
        pass them explicitly to override (rare).
        """
        return ActionRecord(
            id=_new_action_record_id(),
            timestamp=self._now,
            action_type=action_type,
            actor_id=actor_id,
            parameters=dict(parameters),
            succeeded=succeeded,
            side_effects_applied=list(side_effects_applied),
            memories_generated=list(memories_generated),
            initiated_by=initiated_by if initiated_by is not None else self._initiated_by,
            llm_reasoning=llm_reasoning if llm_reasoning is not None else self._llm_reasoning,
        )
